[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store"
